### ISSUE TITLE
...I have no idea how I'm supposed to use this script.

### ISSUE THREAD

**Issue by 017Bluefield** [Lattyware/unrpa#14]
I recently downloaded this script, along with Python 3.7.0. Yet I have no idea what I'm doing; I keep trying to open `unrpa`, but it keeps giving me an invalid syntax error. Without an instruction manual or something, I'm driving completely blind.

**Comment by Lattyware** [comment]
The README contains an example of how to use the script and help on individual arguments. If you still need help, you will need to give me more detail, including exactly how you are running the command (including the full command used), and *all* output - not just "an invalid syntax error" - I would need to see what that error was to say more.

**Comment by ghost** [comment]
For starters, I'm not sure if the `unrpa` I download is _supposed_ to be a `.py` or not. Python doesn't seem to recognize it in the first place.

**Comment by Lattyware** [comment]
You need to be in the directory the script is located - use the `cd` command to change directory until you can see the `unrpa` file when you use `dir`. Then when you run the command it should work.

**Comment by 017Bluefield** [comment]
So this requires some experience with command lines?

(BTW, this was from using PowerShell:)

`PS C:\Users\*******> cd -Path "C:\Users\*******\Downloads\unrpa-1.5.3.zip\unrpa-1.5.3"`
`cd : Cannot find path 'C:\Users\*******\Downloads\unrpa-1.5.3.zip\unrpa-1.5.3' because it does not exist.`
`At line:1 char:1`
`+ cd -Path "C:\Users\*******\Downloads\unrpa-1.5.3.zip\unrpa-1.5.3"`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : ObjectNotFound: (C:\Users\******...zip\unrpa-1.5.3:String) [Set-Location], ItemNotFoundException`
`    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand`

**Comment by Lattyware** [comment]
It's a command line tool, yes.

The error there is telling you what the issue is, that path doesn't exist. I would assume, based on that command, because you are trying to move to a directory in a zip file. An archive isn't a real directory, even if windows explorer depicts it that way.

You need to extract the archive first (copy the files from the archive to a directory), then move to the location you have extracted the files to.

**Comment by 017Bluefield** [comment]
And I do this how? I'm really not sure how to do that.

**Comment by Lattyware** [comment]
I'm sorry, but since I'm offering you this help in my free time for a script I've developed as open source, I'm not going to walk you through every fine detail, it's unreasonable to ask me to walk you through how to do a simple task without any attempt to do so yourself - I would suggest using [google](https://www.google.com/) to search for guides.

**Comment by 017Bluefield** [comment]
[Finally got it working!](https://imgur.com/3PZrlbf) Now it's just a matter of the `.rpa` file.

**Comment by 017Bluefield** [comment]
Okay, finally got it working! I'm sorry for taking up your time.

**Comment by Lattyware** [comment]
It's fine, I have no problem helping, but hopefully you understand I also don't want to just be offering generic computer support to everyone who has issues with my script. I'm happy to help where I'm not just doing google's job by hand.

I'm glad you got it working.
