### ISSUE TITLE
AUR: Unknown key

### ISSUE THREAD

**Issue by TornaxO7** [Lattyware/unrpa#26]
When I'm trying to install it with `trizen` from the AUR it says, that the public key is unknown.

**Comment by Lattyware** [comment]
You need to have my public key in order to verify that the signature is valid.

As per [the comment on the AUR package](https://aur.archlinux.org/packages/unrpa/#comment-628170) you can do this easily with: `gpg --recv-keys 92A57AA673039A4491E6D80E5BDD8CFCA5F0551E`

(Ideally you want to verify that is actually my key too, I am on [keybase](https://keybase.io/latty) which provides some proofs tied to my online presence, and then obviously for future releases if the key hasn't changed you know it is still me.)

Feel free to reopen this issue or create a new one if this wasn't the problem.

**Comment by TornaxO7** [comment]
Dayum! That was a fast response xD 
Thank you! It work's. c(^-^)c
